### ISSUE TITLE
README cleanup

### ISSUE THREAD

**Issue by letmaik** [lsds/sgx-lkl#420]
This meta-issue tracks work related to fixing / simplifying / cleaning up the main project README.

The main idea is to have a short README explaining what SGX-LKL is, plus installation instructions (binary packages), an end-to-end "getting started" sample that's not too complicated, and pointers to other docs for any details or dev-focused topics (like building from source).

- [ ] Add Getting Started sample with pointers to explore details
- [ ] Fix incorrect/outdated sections #395 
- [ ] Move non-Docker flows to separate docs #369
- [ ] Move build-from-source instructions to separate dev doc
- [ ] Move config section (currently mostly empty) to separate docs
- [x] Add section on current limitations
- [ ] Explain app config / host config and sgx-lkl-cfg #351

@jxyang @prp
